version: '{build}'

branches:
  only:
    - main

image:
  - Ubuntu2004

install:
  - ps: git submodule init
  - ps: git submodule update
  - ps: nproc
  - ps: pwd
  - pushd ~
  - svn checkout -r 2980 https://svn.code.sf.net/p/tass64/code/trunk tass64-code
  - cd ~/tass64-code && make -j$(nproc)
  - popd
  - ps: $env:SUFFIX = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:TIMESTAMP = $(git log -1 --format=%cd --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:RELEASE_NAME = "ghouls-tng-"+$env:SUFFIX

build_script:
  - ps: $env:OUTPUT_SSD=$env:RELEASE_NAME+".ssd"
  - ps: $env:OUTPUT_ZIP=$env:RELEASE_NAME+".zip"
  - ps: make ci_build VERBOSE=1 TASS=$HOME/tass64-code/64tass OUTPUT_SSD=$env:OUTPUT_SSD
  - ps: zip -9 $env:OUTPUT_ZIP $env:OUTPUT_SSD
  - env
    
artifacts:
  - path: $(OUTPUT_ZIP)
    name: zip
  - path: $(OUTPUT_SSD)
    name: ssd

deploy:
  - release: $(RELEASE_NAME)
    description: |
      $(APPVEYOR_REPO_COMMIT_MESSAGE)
      
      $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      
    provider: GitHub
    auth_token:
      secure: 4W5gLh9wP/h+mqHPWAnfkq+TdLFmrzC926Z1KZSM8A4HSkZ2bzS+cP/RAUkm9Qao
    artifact: zip,ssd
    draft: false
    prerelease: false
