MODE7:HIMEM=&3C00
*RUN GPSETUP
{?cheat}W%=INKEY-90
*FX119
CODESIZE=150:DIMCODE CODESIZE,BUF 512
FORPASS=0TO2STEP2:P%=CODE:[OPTPASS
.COPY:LDA&F4:PHA:STX&F4:STX&FE30:LDY#0:.COPYLOOP:LDA&8000,Y:STABUF,Y:LDA&8100,Y:STABUF+256,Y:INY:BNECOPYLOOP:PLA:STA&F4:STA&FE30:RTS
.CANWRITE:LDA&F4:PHA:STX&F4:STX&FE30:LDA&8008:EOR#&FF:STA&8008:.CANWRITELOOP:LDY&8008:CPY&8008:BNECANWRITELOOP:SEC:SBC&8008:CMP#1:PLA:STA&F4:STA&FE30:RTS
.WRITE:LDA&F4:PHA:STX&F4:STX&FE30:LDX#&40:.WRITELOOP:.WRITER:LDA&3C00:.WRITEW:STA&8000:INCWRITER+1:INCWRITEW+1:BNEWRITELOOP:INCWRITER+2:INCWRITEW+2:DEX:BNEWRITELOOP:PLA:STA&F4:STA&FE30:RTS
.EMPTY:EQUB13
]IFP%>CODE+CODESIZE:STOP
NEXT
BEST=-1
RELOAD=TRUE
FORX%=0TO15
CALLCOPY
ROM=FALSE:USE=FALSE
A%=BUF+BUF?7:IFA%?0=0:IFA%?1=ASC"(":IFA%?2=ASC"C":IFA%?3=ASC")":ROM=TRUE
IFROM:A%=BUF+9:REPEAT:A%=A%+1:UNTIL?A%=0:?A%=13:NAME=BUF+9:ELSE:NAME=EMPTY
IF$NAME="Ghouls Party {$levels_hash}":IFFNCANWRITE(X%):BEST=X%:RELOAD=FALSE:X%=16:GOTO{$next}
IFLEFT$($NAME,12)="Ghouls Party":IFFNCANWRITE(X%):BEST=X%
IFNOTROM:IFBEST<0:IFFNCANWRITE(X%):BEST=X%
{:next}
NEXT
IFBEST=-1:PRINT"No free sideways RAM bank detected":*BASIC
{?cheat}IFW%:PRINT"Cheat!"
IFNOTRELOAD:PRINT"Reusing sideways RAM bank ";BEST:GOTO{$load}
PRINT"Using sideways RAM bank ";BEST
*LOAD GPARTY0 3C00
X%=BEST:CALLWRITE
{:load}
?{&gp_rom_bank}=BEST
PAGE=&1200:CHAIN"GPARTY"
DEFFNCANWRITE(X%):=((USRCANWRITE)AND&01000000)=0
