MODE7:HIMEM=&3C00
*FX119
CODESIZE=150:DIMCODE CODESIZE,BUF 256
FORPASS=0TO2STEP2:P%=CODE:[OPTPASS
.COPY:LDA&F4:PHA:STX&F4:STX&FE30:LDY#0:.COPYLOOP:LDA&8000,Y:STABUF,Y:INY:BNECOPYLOOP:PLA:STA&F4:STA&FE30:RTS
.CANWRITE:LDA&F4:PHA:STX&F4:STX&FE30:LDA&8008:EOR#&FF:STA&8008:.CANWRITELOOP:LDY&8008:CPY&8008:BNECANWRITELOOP:SEC:SBC&8008:CMP#1:PLA:STA&F4:STA&FE30:RTS
.WRITE:LDA&F4:PHA:STX&F4:STX&FE30:LDX#&40:.WRITELOOP:.WRITER:LDA&3C00:.WRITEW:STA&8000:INCWRITER+1:INCWRITEW+1:BNEWRITELOOP:INCWRITER+2:INCWRITEW+2:DEX:BNEWRITELOOP:PLA:STA&F4:STA&FE30:RTS
]IFP%>CODE+CODESIZE:STOP
NEXT
BEST=-1
FORX%=0TO15
CALLCOPY
ROM=FALSE:USE=FALSE
C=BUF+BUF?7:IFC?0=0:IFC?1=ASC"(":IFC?2=ASC"C":IFC?3=ASC")":ROM=TRUE
NAME$="":IFROM:A%=BUF+9:REPEAT:NAME$=NAME$+CHR$?A%:A%=A%+1:UNTIL?A%=0
IFNAME$="Ghouls Party":IFFNCANWRITE(X%):BEST=X%
IFNOTROM:IFBEST<0:IFFNCANWRITE(X%):BEST=X%
NEXT
IFBEST=-1:PRINT"No free sideways RAM bank detected":*BASIC
PRINT"Using sideways RAM bank ";BEST
*LOAD GPARTY0 3C00
X%=BEST:CALLWRITE
*RUN GPSETUP
?{&gp_rom_bank}=BEST
PAGE=&1200:CHAIN"GPARTY"
DEFFNCANWRITE(X%):=((USRCANWRITE)AND&01000000)=0
